from __future__ import annotations

from typing import Any

from .tokenizer import TOKENIZERS


def compile_task_view(
    note: dict[str, Any], task: str, preferred_layer: int, max_tokens: int, profile: str = "generic"
) -> tuple[int, str]:
    """Select whole representations; never splice command blocks or drop qualifications.

    A task-specific extract is usable only when the author has provided a complete
    representation. Otherwise select a complete lower layer instead of lossy sentences.
    """
    metadata = note.get("metadata", {})
    preconditions = metadata.get("preconditions", [])
    if isinstance(preconditions, str):
        preconditions = [preconditions]
    qualification = "\n".join(f"Precondition: {value}" for value in preconditions)
    for layer in range(preferred_layer, -1, -1):
        text = str(note.get(f"l{layer}") or "").strip()
        # L0 generated by legacy versions may be truncated, so prefer the full summary.
        if layer == 0:
            text = str(note.get("summary") or text).strip()
        if not text:
            continue
        if qualification:
            text = qualification + "\n" + text
        for field in ("verification", "rationale"):
            value = metadata.get(field)
            if isinstance(value, str) and value.strip() and value.strip() not in text:
                text += f"\n{field.title()}: {value.strip()}"
        if TOKENIZERS.count(text, profile).tokens <= max_tokens:
            return layer, text
    return 0, ""
